font_family      family=MonoLisa postscript_name=MonoLisa-Regular
bold_font        family=MonoLisa postscript_name=MonoLisa-Bold
italic_font      family=MonoLisa postscript_name=MonoLisa-Italic
bold_italic_font family=MonoLisa postscript_name=MonoLisa-BoldItalic

# Застосовуємо всі обрані фічі до чотирьох основних статичних стилів
font_features MonoLisa-Regular +calt +liga +cv01 +cv02 +cv03 +cv04 +cv05 +cv06 +cv07 +cv08 +cv09 +cv10 +cv11 +dlig +ss04 +ss11 +ss13 +zero
font_features MonoLisa-Bold +calt +liga +cv01 +cv02 +cv03 +cv04 +cv05 +cv06 +cv07 +cv08 +cv09 +cv10 +cv11 +dlig +ss04 +ss11 +ss13 +zero
font_features MonoLisa-Italic +calt +liga +cv01 +cv02 +cv03 +cv04 +cv05 +cv06 +cv07 +cv08 +cv09 +cv10 +cv11 +dlig +ss04 +ss11 +ss13 +zero
font_features MonoLisa-BoldItalic +calt +liga +cv01 +cv02 +cv03 +cv04 +cv05 +cv06 +cv07 +cv08 +cv09 +cv10 +cv11 +dlig +ss04 +ss11 +ss13 +zero

font_size 13.0

# ─── Ligatures ──────────────────────────────────────
disable_ligatures cursor
# "cursor" = ligatures show while reading, break apart
# under the cursor so you can edit individual chars.
# Use "never" if you want them always on.

# ─── Smooth Cursor ──────────────────────────────────
cursor_shape           block
cursor_blink_interval 0.5 ease-in-out
cursor_stop_blinking_after 15.0
cursor_trail           150
cursor_trail_decay     0.08 0.33

shell /usr/bin/fish

# ─── Window ─────────────────────────────────────────
window_padding_width  8
window_margin_width   4
single_window_margin_width 0


# ─── Tab Bar ────────────────────────────────────────
tab_bar_style         powerline
tab_powerline_style   slanted
tab_title_template    "{index}: {title}"

# ─── Misc ───────────────────────────────────────────
enable_audio_bell     no
visual_bell_duration  0.0
scrollback_lines      10000
mouse_hide_wait       3.0
url_style             curly
copy_on_select        yes


# ─── Tokyo Night ────────────────────────────────────
foreground #a9b1d6
background #1a1b26

color0 #414868
color1 #f7768e
color2 #73daca
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #c0caf5

color8 #414868
color9 #f7768e
color10 #73daca
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

cursor #c0caf5
cursor_text_color #1a1b26

selection_foreground none
selection_background #28344a

url_color #9ece6a

active_border_color #3d59a1
inactive_border_color #101014
bell_border_color #e0af68

tab_bar_style fade
tab_fade 1
active_tab_foreground   #3d59a1
active_tab_background   #16161e
active_tab_font_style   bold
inactive_tab_foreground #787c99
inactive_tab_background #16161e
inactive_tab_font_style bold
tab_bar_background #101014
